monitor=eDP-1,1920x1080@60,0x0,1
monitor=eDP-1,addreserved,0,0,48,0

exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2
exec-once=swaybg -i $HOME/Pictures/Wallpaper/green.jpg
exec-once=eww daemon
exec-once=eww open bar
exec-once=dunst

input {
  follow_mouse=1
}

general {
  sensitivity=1
  gaps_in=6
  gaps_out=12
  border_size=4
  col.active_border=0x73E2A733
  col.inactive_border=0x1C7C5433
}

decoration {
  rounding=8
  blur=3
  drop_shadow=0
  shadow_range=60
  col.shadow=0x66000000
}

animations {
  enabled=1
  #animation=windows,1,4,default,slide
  #animation=borders,1,5,default
  #animation=windows,fadein,1,5,default
  #animation=workspaces,1,3,default,vertslide
}

dwindle {
  pseudotile=0
}

bind=SUPER,Return,exec,alacritty
bind=SUPERSHIFT,Q,killactive,
bind=SUPER,V,togglefloating,
bind=SUPER,C,exec,grimshot --notify copy area,
bind=SUPER,D,exec,wofi --show run --xoffset=1670 --yoffset=12 --width=230px --height=984 --style=$HOME/.config/wofi.css --term=footclient --prompt=Run
bind=SUPER,F,fullscreen,0

bind=SUPER,h,movefocus,l
bind=SUPER,l,movefocus,r
bind=SUPER,k,movefocus,u
bind=SUPER,j,movefocus,d

bind=SUPERSHIFT,h,movewindow,l
bind=SUPERSHIFT,l,movewindow,r
bind=SUPERSHIFT,k,movewindow,u
bind=SUPERSHIFT,j,movewindow,d

bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,7

bind=SUPERSHIFT,exclam,movetoworkspacesilent,1
bind=SUPERSHIFT,at,movetoworkspacesilent,2
bind=SUPERSHIFT,numbersign,movetoworkspacesilent,3
bind=SUPERSHIFT,dollar,movetoworkspacesilent,4
bind=SUPERSHIFT,percent,movetoworkspacesilent,5

bind=,XF86MonBrightnessUp,exec,brightnessctl set +5%
bind=,XF86MonBrightnessDown,exec,brightnessctl set 5%-
bind=,XF86AudioRaiseVolume,exec,amixer -i 5
bind=,XF86AudioLowerVolume,exec,amixer -d 5
